
import type { Metadata } from "next";
import Image from "next/image";
import LogoMain from "@/public/weblogo/Mainlogo.svg"
import LogoSmall from "@/public/weblogo/logomain.svg"
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ToOrder from "@/components/ToOrder";
import { Montserrat, Inter } from "next/font/google";
import PhoneImg from "@/public/weblogo/phone.svg"
import BackgroundImage from "@/public/weblogo/bg-1.png"


export const metadata: Metadata = {
  title: "Prontodev",
  description: "Generated by create next app",
};
const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  variable: "--font-montserrat",
});

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter-source",
});

const navLinks = [
  { href: "/", label: "Main" },
  { href: "/about", label: "About us" },
  { href: "/contact", label: "Contact us" },
  { href: "/faq", label: "FQA" },
];


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`antialiased  ${montserrat.className}`}
      >
        <header className={`flex items-center w-full 2xl:h-[173px] xl:h-[120px] lg:h-[80px] justify-between p-1.5 xm:py-3 xm:px-[12px] lg:px-[82px]`}>
          <Link href={"/"} className="block shrink-0">
            <Image
              src={LogoMain.src}
              width={440}
              height={75}
              priority
              alt="logo"
              className="h-auto xm:w-[230px] xs:w-[330px]  w-[440px] xl:w-[280px] lg:w-[230px] 2xl:w-[440px] block md:hidden lg:block"
            />
            <Image
              src={LogoSmall.src}
              width={100}
              height={100}
              priority
              alt="logo"
              className="h-auto xm:w-[80px] xl:w-[280px] lg:w-[200px] 2xl:w-[440px] xm:hidden md:block lg:hidden"
            />
          </Link>
          <nav className="hidden items-center md:block">
            <ul className="flex text-black 2xl:text-[26px] lg:text-[20px]  md:text-[22px] xl:text-[24px] items-center xm:max-xs:justify-between xm:max-xs:pr-2">
              {navLinks.map((link, index) => {
                if (index != 0) {
                  return (
                    <li key={link.href} className={index === 0 ? "ml-9 xs:max-sm:ml-3" : ""}>
                      <Link href={link.href} className="hover:text-hover-gray p-3 xm:max-xs:p-0">
                        {link.label}
                      </Link>
                    </li>
                  )
                }
              })}
            </ul>
          </nav>
          <details className="mobile-menu relative md:hidden">
            <summary
              className="flex h-11 w-11 cursor-pointer list-none items-center justify-center rounded border border-[#d8d8d8]"
              aria-label="Open navigation menu"
            >
              <span className="mobile-menu__icon" aria-hidden="true"></span>
            </summary>
            <ul className="absolute right-0 top-[52px] z-20 w-[190px] rounded border border-[#d8d8d8] bg-white py-2 text-[18px] shadow-lg">
              {navLinks.map((link) => (
                <li key={link.href}>
                  <Link href={link.href} className="block px-4 py-3 text-black hover:text-hover-gray">
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </details>
          <div className="hidden md:flex">
            <Image
              src={PhoneImg.src}
              width={46}
              height={46}
              alt="phone logo"
              className="lg:w-[35px] xl:w-[46px] md:w-[25px]"
            />
            <a
              href="tel:+15879695446"
              className={`ml-2 inline-flex h-[57px] items-center gap-1 overflow-hidden pr-5 text-[22px] font-bold text-[#1A4E95] ${inter.className}`}
            >+1 587 969 5446</a>
          </div>
        </header>
        <div className=" relative">
          {children}
        </div>
        <footer className="bg-blue border-t pt-9 px-5 text-white relative z-10">
          <div className="flex justify-around pb-5 xm:max-md:flex-col xm:max-md:text-center">
            <div className="xm:max-md:mb-6">
              <h3 className="text-[26px] md:max-lg:text-2xl  mb-4 xm:max-md:mb-2">Navigation</h3>
              <ul className="w-full text-white text-[20px] md:max-lg:text-xl xm:max-xs:text-[18px] items-center">
                <li className="">
                  <Link href={"/about"} className="hover:text-hover-gray">
                    About us
                  </Link>
                </li>
                <li className="">
                  <Link href={"/contact"} className="hover:text-hover-gray">
                    Contact us
                  </Link>
                </li>
                <li className="">
                  <Link href={"/faq"} className="hover:text-hover-gray" >
                    FAQ
                  </Link>
                </li>
              </ul>
            </div>
            <div className="xm:max-md:mb-6">
              <h3 className="text-[26px] md:max-lg:text-2xl mb-4 xm:max-md:mb-2">Contact Us!</h3>
              <ul className="w-full text-white text-[20px] md:max-lg:text-xl xm:max-xs:text-[18px] items-center">
                <li className="">
                  Email: contact@prontodev.dev

                </li>
                <li className="">
                  Phone: +1 587 969 5446
                </li>
                <li className="">
                  Whats up:
                </li>
              </ul>
            </div>
            <div className="xm:max-md:mb-6">
              <h3 className="text-[26px] md:max-lg:text-2xl mb-4 xm:max-md:mb-2">Other information</h3>
              <ul className="w-full text-white text-[20px] md:max-lg:text-xl items-center xm:max-xs:text-[18px]">
                <li className="">
                  Linkedin:
                </li>
                <li className="">
                  Upwork:
                </li>
                <li className="">
                  FAQ
                </li>
              </ul>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
