

import type { Metadata } from "next";
import Image from "next/image";
import logoMain from "@/public/weblogo/Mainlogo.svg"
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ToOrder from "@/components/ToOrder";
import { Montserrat } from "next/font/google";
import PhoneImg from "@/public/weblogo/phone.svg"

export const metadata: Metadata = {
  title: "Prontodev",
  description: "Generated by create next app",
};
const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  variable: "--font-montserrat",
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`antialiased max-w-[1920px] m-auto ${montserrat.className}`}
      >
        <header className="flex items-center  w-full 2xl:h-[173px] justify-between p-1.5 px-[82px]">
          <Link href={"/"} className="block shrink-0">
            <Image
              src={logoMain.src}
              width={440}
              height={75}
              priority
              alt="logo"
              className="h-auto w-[440px] xl:w-[280px] lg:w-[200px] 2xl:w-[440px]"
            />
          </Link>
          <nav className="items-center">
            <ul className="flex text-black 2xl:text-[26px] lg:text-[20px] xm:max-xs:text-[18px] items-center xm:max-xs:justify-between xm:max-xs:pr-2">
              <li className="ml-9 xs:max-sm:ml-3">
                <Link href={"/about"} className="hover:text-hover-gray p-3 xm:max-xs:p-0">
                  About us
                </Link>
              </li>
              <li className="">
                <Link href={"/contact"} className="hover:text-hover-gray p-3 xm:max-xs:p-0">
                  Contact us
                </Link>
              </li>
              <li className="">
                <Link href={"/faq"} className="hover:text-hover-gray p-3 xm:max-xs:p-0">
                  FQA
                </Link>
              </li>
            </ul>
          </nav>
          <div className="flex">
            <Image
              src={PhoneImg.src}
              width={46}
              height={46}
              alt="phone logo"
            />
            <a
              href="tel:+15879695446"
              className="ml-2 inline-flex h-[57px] items-center gap-1 overflow-hidden pr-5 text-[22px] font-bold text-[#1A4E95]"
            >+1 587 969 5446</a>
          </div>

        </header>
        <div className="px-3 xm:max-xs:px-[12px] max-w-[1464px] m-auto">
          {children}
        </div>
        <footer className="border-t-gray-300 border-t pt-9 px-5">
          <div className="flex justify-around mb-5 xm:max-md:flex-col xm:max-md:text-center">
            <div className="xm:max-md:mb-6">
              <h3 className="text-3xl md:max-lg:text-2xl  mb-4 xm:max-md:mb-2">Navigation</h3>
              <ul className="w-full text-gray text-2xl md:max-lg:text-xl xm:max-xs:text-[18px] items-center">
                <li className="">
                  <Link href={"/about"} className="hover:text-hover-gray">
                    About us
                  </Link>
                </li>
                <li className="">
                  <Link href={"/contact"} className="hover:text-hover-gray">
                    Contact us
                  </Link>
                </li>
                <li className="">
                  <Link href={"/faq"} className="hover:text-hover-gray" >
                    FAQ
                  </Link>
                </li>
              </ul>
            </div>
            <div className="xm:max-md:mb-6">
              <h3 className="text-3xl md:max-lg:text-2xl mb-4 xm:max-md:mb-2">Contact Us!</h3>
              <ul className="w-full text-gray text-2xl md:max-lg:text-xl xm:max-xs:text-[18px] items-center">
                <li className="">
                  Email: contact@prontodev.dev

                </li>
                <li className="">
                  Phone: +1 587 969 5446
                </li>
                <li className="">
                  Whats up:
                </li>
              </ul>
            </div>
            <div className="xm:max-md:mb-6">
              <h3 className="text-3xl md:max-lg:text-2xl mb-4 xm:max-md:mb-2">Other information</h3>
              <ul className="w-full text-gray text-2xl md:max-lg:text-xl items-center xm:max-xs:text-[18px]">
                <li className="">
                  Linkedin:
                </li>
                <li className="">
                  Upwork:
                </li>
                <li className="">
                  FAQ
                </li>
              </ul>
            </div>
          </div>
          <span>
            logos been taken from https://www.flaticon.com
          </span>
        </footer>
      </body>
    </html>
  );
}
